-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public."Student"
(
    username character varying(30) NOT NULL,
    student_name character varying(30) NOT NULL,
    first_name character varying(15) NOT NULL,
    last_name character varying(15) NOT NULL,
    email character varying(40) NOT NULL,
    PRIMARY KEY (username)
);

CREATE TABLE IF NOT EXISTS public."Employee"
(
    username character varying(30) NOT NULL,
    first_name character varying(15) NOT NULL,
    last_name character varying(15) NOT NULL,
    password character varying(40) NOT NULL,
    email character varying(40) NOT NULL,
    PRIMARY KEY (username)
);

CREATE TABLE IF NOT EXISTS public."Hall"
(
    hall_name character varying(40) NOT NULL,
    num_of_rooms integer NOT NULL DEFAULT 0,
    PRIMARY KEY (hall_name)
);

CREATE TABLE IF NOT EXISTS public."Study_Room"
(
    room_num integer NOT NULL,
    hall_name character varying(40) NOT NULL,
    occupied boolean NOT NULL,
    flag boolean NOT NULL,
    PRIMARY KEY (room_num, hall_name)
);

CREATE TABLE IF NOT EXISTS public."Schedule_Room"
(
    schedule_id integer NOT NULL,
    username character varying(30) NOT NULL,
    scheduled_time tsrange NOT NULL,
    room_num integer NOT NULL,
    room_hall character varying(40) NOT NULL,
    CONSTRAINT pk_schedule_id PRIMARY KEY (schedule_id)
);

CREATE TABLE IF NOT EXISTS public."Employee_Check_Study_Room"
(
    employee_username character varying(30) NOT NULL,
    room_num integer NOT NULL,
    room_hall character varying(40) NOT NULL,
    date_corrected timestamp without time zone NOT NULL,
    PRIMARY KEY (employee_username, room_num, room_hall)
);

CREATE TABLE IF NOT EXISTS public."Study_Room_History"
(
    room_num integer NOT NULL,
    hall_name character varying(40) NOT NULL,
    date_time timestamp without time zone NOT NULL,
    occupied boolean NOT NULL,
    flag boolean NOT NULL,
    PRIMARY KEY (room_num, hall_name, date_time)
);

ALTER TABLE IF EXISTS public."Study_Room"
    ADD CONSTRAINT fk_hall FOREIGN KEY (hall_name)
    REFERENCES public."Hall" (hall_name) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE
    NOT VALID;


ALTER TABLE IF EXISTS public."Schedule_Room"
    ADD CONSTRAINT fk_username FOREIGN KEY (username)
    REFERENCES public."Student" (username) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE
    NOT VALID;


ALTER TABLE IF EXISTS public."Schedule_Room"
    ADD CONSTRAINT fk_room_id FOREIGN KEY (room_num, room_hall)
    REFERENCES public."Study_Room" (room_num, hall_name) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE
    NOT VALID;


ALTER TABLE IF EXISTS public."Employee_Check_Study_Room"
    ADD CONSTRAINT fk_study_room FOREIGN KEY (room_num, room_hall)
    REFERENCES public."Study_Room" (room_num, hall_name) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE
    NOT VALID;


ALTER TABLE IF EXISTS public."Employee_Check_Study_Room"
    ADD CONSTRAINT fk_employee FOREIGN KEY (employee_username)
    REFERENCES public."Employee" (username) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE
    NOT VALID;


ALTER TABLE IF EXISTS public."Study_Room_History"
    ADD CONSTRAINT fk_study_room FOREIGN KEY (room_num, hall_name)
    REFERENCES public."Study_Room" (room_num, hall_name) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE
    NOT VALID;

END;